### ISSUE TITLE
Update entry_id to use CID instead of UUID

### ISSUE THREAD

**Issue by RobStallion** [dwyl/alog#32]
Relates to https://github.com/dwyl/alog/issues/15, https://github.com/dwyl/cid/issues/1, https://github.com/dwyl/auth/issues/25 & https://github.com/dwyl/cid/issues/11

Replace/update alog so that it creates CIDs based on the content passed to it instead of creating UUIDs. 

Will be using [this branch](https://github.com/dwyl/cid/pull/21) to test this for now. This can be updated later once we have a our CID module working as we would like. For now just wanted to get a better understanding of how this functionality will work in alog.

The way alog currently inserted into a database will need to be updated to look something like this...

| `inserted ` | **`cid`**(PK)<sup>1</sup> | **`name`** | **`address`** | **`prev`** |
| ----------- | ----------- | ----------- | ----------- |-----|
| 1541609554 | **gVSTedHFGBetxy** | Bruce Wane | 1007 Mountain Drive, Gotham | null |
| 1541618643 | smnELuCmEaX42 | Bruce Wane | [Rua Goncalo Afonso, Vila Madalena, Sao Paulo, 05436-100, Brazil](https://www.tripadvisor.co.uk/ShowUserReviews-g303631-d2349935-r341872180-Batman_Alley-Sao_Paulo_State_of_Sao_Paulo.html "Batman Alley ;-)") | **gVSTedHFGBetxy** |

See the [faqs section](https://github.com/dwyl/cid#faqs) of the CID readme for more info on this point.

**Comment by RobStallion** [comment]
### Code that will need to change 

- line 82 - replace `:entry_id` with cid. Also update relevant documentation. 
- `insert_entry_id/1` in insert needs to be replaced with `DwylCid.cid/1` (the current function I'm using to create CIDs. Will likely change)

insert looks like we would have to remove the `insert_entry_id/1` function (this function can probably be removed from the app completely as well no longer be used)

Where is user being defined in the tests? (insert_test.exs)
```elixir
  describe "insert/1 - with changeset:" do
    test "succeeds" do
      assert {:ok, user} = %User{} |> User.changeset(Helpers.user_1_params()) |> User.insert()
    end
  end
```

**Comment by nelsonic** [comment]
@RobStallion thank you for opening this issue. ✨ 
Please focus on the open pull requests in CID **`before`** doing any work on **alog**. 
![image](https://user-images.githubusercontent.com/194400/51854722-52b60980-2323-11e9-925a-723b9ac829ae.png)

We need to _re-think_ how alog works and unless you have a decent amount of experience with both _existing_ CMS and Ecto internals you won't accidentally stumble upon the optimal solution to this problem.

**Comment by RobStallion** [comment]
Closing this issue in favour of 
https://github.com/dwyl/phoenix-ecto-append-only-log-example/issues/23
and
https://github.com/dwyl/phoenix-ecto-append-only-log-example/issues/22

**Comment by nelsonic** [comment]
@RobStallion thanks for consolidating the issue into the example first. 👍
